Create event Screen
FEUP-ESOF-2020-21/open-cx-t4g5-teenage-mutant-coding-turtles pull request #30
Opened 2020-12-07 19:15 UTC by joaorenatopinto

FIrst draft of the Create Screen Event. Navigation to it with FAB on events Screen, after a successful submission goes back to it.

![Create Event Screen](https://user-images.githubusercontent.com/36915919/101394469-7acc0780-38c0-11eb-8c24-eaeb692e5e1f.png)

closes #24

2020-12-07 23:46 UTC, jf-ne-du-vp requested changes

2020-12-07 23:46 UTC, jf-ne-du-vp commented on src/netfair/lib/create_event_screen.dart
> +              child: Text('Create a Event',
typo, should "Create an event"

2020-12-08 16:54 UTC, joaorenatopinto commented on src/netfair/lib/create_event_screen.dart
> +              child: Text('Create a Event',
Typo fix

2020-12-08 16:59 UTC, jf-ne-du-vp approved these changes

2020-12-08 17:00 UTC, merged